name: main

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: chuhlomin/search

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'

      - name: Run tests
        run: |
          go vet ./...
          go test -v -cover ./...

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        with:
          username: chuhlomin
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest
