name: release

on:
  push:
    tags:
      - '*'
      
env:
  DOCKER_IMAGE: chuhlomin/search

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the tag
        id: tag
        run: echo ::set-output name=value::${GITHUB_REF/refs\/tags\//}

      - name: Login to CR
        uses: docker/login-action@v1
        with:
          username: chuhlomin
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: ${{ steps.tag.outputs.value }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
